# Generated by Django 3.2.6 on 2021-08-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryCounterSystemApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='lastname',
        ),
    ]
